name: Actions Workflow

on: [push]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
          - name: Simple JS Action
            id: greet
            uses: actions/hello-world-javascript-action@ad41a6c
            with:
              who-to-greet: 'Mona the Octocat'
          - name: Log Greetings Time
            run: echo "{{ steps.greet.outputs.time }}"
