name: Actions Workflow
on:
  push:
  pull_request:
      types: [closed, opened, reopened, assigned]
  issues:
    types: [assigned, unassigned, opened, reopened, deleted , demilestoned]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
          - name: List the files
            run: |
              ls -lart
              pwd
              echo $GITHUB_SHA
              echo $GITHUB_WORKSPACE
              echo $GITHUB_REPOSITORY
              echo "${{ github.token }}"
          - name: Checkout
            uses: actions/checkout@v2.3.3
          - name: List the files after checkout
            run: |
              ls -lart
              pwd
          - name: Simple JS Action
            id: greet
            uses: actions/hello-world-javascript-action@main
            with:
              who-to-greet: 'Mona the Octocat'
          - name: Log Greetings Time
            run: echo "${{ steps.greet.outputs.time }}"
