name: Actions Workflow

on: [push]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
          - name: List the files
            run: |
              ls -lrt
              pwd
          - name: Simple JS Action
            id: greet
            uses: actions/hello-world-javascript-action@main
            with:
              who-to-greet: 'Mona the Octocat'
          - name: Log Greetings Time
            run: echo "${{ steps.greet.outputs.time }}"
