name: Container

on: push

jobs:
  docker-steps:
    runs-on: self-hosted
    container:
      image: node:14.13.1-alpine3.10
    steps:
      - name: log node version
        run: node -v
      - name: step with docker
        uses: docker://node:12.19.0-alpine3.10
        with: 
          entrypoint: '/bin/echo'
          arg: 'Hello World'
      - name: Log node version 2 
        uses: docker://node:12.19.0-alpine3.10
        with: 
          entrypoint: '/usr/local/bin/node'
          args: '-v'
  node-docker:
    runs-on: self-hosted
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
            - 27017:27017
    steps:
        - name: Post a user
          run: 'curl -X POST http://localhost:3001/api/user -H ''Content-type: application/json'' -d '' {"username": "hello" , "address:" "abcabc" }'''
        - name: Get users
          run: curl http://localhost:3001/api/users