name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:12.19.0-alpine3.10

    steps:
        - name: Log Node Version
          run: | 
            node -v
            npm -v
            cat /etc/os-release

