name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix: 
        os: [macos-latest , ubuntu-latest , wwindows-latest]
        node-version: [ 6 , 8 , 10 ]
    runs-on: {{ matrix.os }}
    steps:
        - name: Log node version
          run: node -v
        - uses: actions/setup-node@v1
          with:
            node-version: '8'
        - name: Log node version
          run: node -v